spring:
  redis:
    host: 127.0.0.1
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 2
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最大连接数
        max-active: 80
    port: 6379
  application:
    name: red
server:
  compression:
    min-response-size: 100
    enabled: false
    mime-types: application/json

distributed:
  scheduled:
    enable: open
    appName: xxxx




